DROP DATABASE IF EXISTS bookish_dataBase;
CREATE DATABASE bookish_dataBase;

USE bookish_dataBase;

CREATE TABLE Books(
	BookID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BookName VARCHAR(255) NOT NULL,
	Barcode VARCHAR(255) NOT NULL,
	ISBN int NOT NULL,
	Author VARCHAR(255) NOT NULL
);

CREATE TABLE Users(
	UserID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(255) NOT NULL

);

CREATE TABLE Copies(
	CopyID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	BookID INT NOT NULL,
	FOREIGN KEY (BookID) REFERENCES Books(BookID),

);

CREATE TABLE Checkouts(
	CheckOutID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CopyID INT NOT NULL,
	FOREIGN KEY (CopyID) REFERENCES Copies(CopyID),
	DueDateReturn DATETIME NOT NULL
);




