USE bookish_dataBase;

CREATE TABLE Books(
	Book_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Book_Name VARCHAR(255) NOT NULL
);

CREATE TABLE Users(
	UserID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	USerName VARCHAR(255) NOT NULL
);

CREATE TABLE Copies(
	CopyID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	BookID INT NOT NULL,
	FOREIGN KEY (BookID) REFERENCES Books(Book_ID),

);

CREATE TABLE Checkouts(
	CheckOutID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CopyID INT NOT NULL,
	FOREIGN KEY (CopyID) REFERENCES Copies(CopyID),
	Due_Date_Return DATETIME NOT NULL
);




